### ISSUE TITLE
关于mongoTemplate初始化的问题

### ISSUE THREAD

**Issue by coldxiangyu** [nintha/springboot-logging-mongo-example#2]
在[ApplicationContext] Autowire MongoTemplate, MongoAppender is ready.输出的时候setApplicationContext已经执行，springboot启动完毕之后mongoTemplate应该是非空的。但是如果改成web工程的话，项目启动以后在controller中打印的log依然无法保存到mongo，mongoTemplate还是null，请问是什么原因造成的

**Comment by nintha** [comment]
mongoTemplate 注入是通过实现ApplicationContextAware接口，接受setApplicationContext事件来完成的。
你可以在setApplicationContext里打印下mongoTemplate。

另外springboot本身就可以提供web服务，我不太理解问题中‘web工程’的含义。

可以的话，请提供下最小化可复现代码。

**Comment by coldxiangyu** [comment]
就是在工程中添加web依赖（spring-boot-starter-web），加上controller层，在controller层加日志输出，在浏览器url进行请求的时候，控制台打印日志，但是没有在mongo中存储。

**Comment by nintha** [comment]
文字描述没法保证复现错误的，请提供下最小化可复现代码，谢谢。

**Comment by coldxiangyu** [comment]
已经上传我的github，工程名是mongolog，谢谢~

**Comment by nintha** [comment]
你试试把spring-boot-devtool依赖去掉。

**Comment by coldxiangyu** [comment]
去掉之后可以了，能告知一下spring-boot-devtool是怎么影响的吗？
再次表示感谢。

**Comment by nintha** [comment]
热重载用了ClassLoader，没法保证静态变量mongoTemplate在同一个类里面，logback加载的和spring加载的其实是两个类名不一样的对象
